# Config file for air.

# Working directory
root = "."

# File extensions for monitoring.
includes = [
    "**/*.go",
    "**/*.tmpl",
    "**/*.html"
]

# Directories to exclude from monitoring.
excludes = [
    "vendor",
    "node_modules",
    "public",
    "tmp"
]

# Command to run.
cmd = "sh -c 'go build -o tmp/main cmd/api/main.go && ./tmp/main'"

# Log file to write the output of the command.
log = "air.log"

# The amount of time in milliseconds to wait after changes before restarting.
delay = 200

# Enable debug logs
debug = true

# The shell to use for running commands.
shell = "sh"
